# Generated by Django 3.2.4 on 2021-07-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=64, verbose_name='Coin name')),
                ('market1', models.CharField(max_length=32, verbose_name='Market 1')),
                ('market2', models.CharField(max_length=32, verbose_name='Market 2')),
                ('volume', models.FloatField(verbose_name='Market volume')),
                ('profit', models.FloatField(verbose_name='Profit')),
            ],
        ),
    ]
