# Generated by Django 3.2.4 on 2021-07-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserResponse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitsituation',
            name='volume',
            field=models.IntegerField(verbose_name='Market volume'),
        ),
    ]
